/**
 * templeData.ts
 * COMPREHENSIVE: All 12 Jyotirlingas, 51 Shakti Peeths, 4 Dham, Chota Char Dham, Major Temples
 * Each temple has youtubeChannelId, youtubePlaylistId, searchKeywords for live/recorded aarti
 * Latest video IDs refreshed via auto-refresh system
 */

import { TempleStream } from '../types/devotionalTypes';

const now = new Date().toISOString();

// ===== 12 JYOTIRLINGAS =====
const jyotirlingas: TempleStream[] = [
  {
    id: 'somnath-jyotirlinga',
    templeName: 'Somnath Temple',
    hindiName: '\u0938\u094B\u092E\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Gujarat',
    city: 'Prabhas Patan',
    category: 'jyotirlinga',
    templeNumber: 1,
    significance: 'First and most sacred of the 12 Jyotirlingas. Rebuilt 17 times. Lord of the Soma (Moon).',
    officialWebsite: 'https://somnath.org/',
    website: 'https://somnath.org/',
    address: 'Somnath Mandir Road, Prabhas Patan, Gujarat 362268',
    phone: '+91-2876-231212',
    youtubeChannelId: 'UC7fG5s8UJdEYN5O0J1Y3XwQ',
    youtubeSearchKeywords: 'Somnath Temple live darshan aarti 2026',
    latestVideoId: 'Tllop3z4Jok',
    latestVideoTitle: 'Live Darshan - Shree Somnath Temple, First Jyotirlinga',
    latestVideoThumbnail: 'https://img.youtube.com/vi/Tllop3z4Jok/maxresdefault.jpg',
    latestVideoUploadedAt: now,
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/Tllop3z4Jok/maxresdefault.jpg',
    latitude: 20.8880,
    longitude: 70.4012,
    description: 'The first and most sacred of the 12 Jyotirlingas. Built by the Moon God Chandra, destroyed and rebuilt 17 times. A symbol of resilience and eternal faith.',
    aartiTimings: [
      { type: 'Mangala', startTime: '07:00 AM', duration: 30, officialUrl: 'https://somnath.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://somnath.org/' },
      { type: 'Sandhya', startTime: '07:00 PM', duration: 30, officialUrl: 'https://somnath.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '07:00 PM', hoursUntil: 2 }
  },
  {
    id: 'mallikarjuna-jyotirlinga',
    templeName: 'Mallikarjuna Temple',
    hindiName: '\u092E\u0932\u094D\u0932\u093F\u0915\u093E\u0930\u094D\u091C\u0941\u0928 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Andhra Pradesh',
    city: 'Srisailam',
    category: 'jyotirlinga',
    templeNumber: 2,
    significance: 'Where Shiva and Parvati reunited. Confluence of Shaivism and Shaktism on Krishna River banks.',
    officialWebsite: 'https://srisailamtemple.com/',
    website: 'https://srisailamtemple.com/',
    address: 'Srisailam, Nallamala Hills, Andhra Pradesh 528101',
    youtubeSearchKeywords: 'Mallikarjuna Srisailam live darshan aarti',
    latestVideoId: '',
    latestVideoTitle: 'Mallikarjuna Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Mallikarjuna_Temple%2C_Srisailam.jpg/800px-Mallikarjuna_Temple%2C_Srisailam.jpg',
    latitude: 16.0740,
    longitude: 78.8680,
    description: 'One of the 12 Jyotirlingas and one of the 18 Maha Shakti Peethas. Located on the Nallamala Hills, where Lord Shiva and Goddess Parvati reunited.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://srisailamtemple.com/' },
      { type: 'Shringar', startTime: '06:30 AM', duration: 45, officialUrl: 'https://srisailamtemple.com/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://srisailamtemple.com/' },
      { type: 'Sandhya', startTime: '06:30 PM', duration: 30, officialUrl: 'https://srisailamtemple.com/' },
      { type: 'Isha', startTime: '09:00 PM', duration: 20, officialUrl: 'https://srisailamtemple.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:30 PM', hoursUntil: 3 }
  },
  {
    id: 'mahakaleshwar-jyotirlinga',
    templeName: 'Mahakaleshwar Temple',
    hindiName: '\u092E\u0939\u093E\u0915\u093E\u0932\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Madhya Pradesh',
    city: 'Ujjain',
    category: 'jyotirlinga',
    templeNumber: 3,
    significance: 'Only south-facing (Dakshinamukhi) Jyotirlinga. Famous for Bhasma Aarti at dawn.',
    officialWebsite: 'https://www.shrimahakaleshwar.mp.gov.in/',
    website: 'https://www.shrimahakaleshwar.mp.gov.in/',
    address: 'Mahankal Mandir, Jaisinghpura, Ujjain, Madhya Pradesh 456001',
    phone: '+91-734-2550103',
    youtubeSearchKeywords: 'Mahakaleshwar Ujjain live bhasma aarti',
    latestVideoId: 'RRe75bSFzGQ',
    latestVideoTitle: 'Mahakaleshwar Bhasma Aarti Live',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/RRe75bSFzGQ/maxresdefault.jpg',
    latitude: 23.1827,
    longitude: 75.7682,
    description: 'The only south-facing Jyotirlinga, known for the powerful Bhasma Aarti performed at dawn with sacred ash. One of the most spiritually charged temples in India.',
    aartiTimings: [
      { type: 'Mangala', startTime: '03:30 AM', duration: 45, officialUrl: 'https://www.shrimahakaleshwar.mp.gov.in/' },
      { type: 'Shringar', startTime: '08:30 AM', duration: 45, officialUrl: 'https://www.shrimahakaleshwar.mp.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://www.shrimahakaleshwar.mp.gov.in/' },
      { type: 'Sandhya', startTime: '06:30 PM', duration: 30, officialUrl: 'https://www.shrimahakaleshwar.mp.gov.in/' },
      { type: 'Isha', startTime: '09:00 PM', duration: 20, officialUrl: 'https://www.shrimahakaleshwar.mp.gov.in/' },
    ],
    nextAarti: { type: 'Mangala', startTime: '03:30 AM', hoursUntil: 0.5 }
  },
  {
    id: 'omkareshwar-jyotirlinga',
    templeName: 'Omkareshwar Temple',
    hindiName: '\u0913\u0902\u0915\u093E\u0930\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Madhya Pradesh',
    city: 'Omkareshwar',
    category: 'jyotirlinga',
    templeNumber: 4,
    significance: 'Located on an island shaped like the sacred Om symbol in the Narmada River.',
    officialWebsite: 'https://omkareshwar.in/',
    website: 'https://omkareshwar.in/',
    address: 'Sri Omkareshwar Temple, Mandhata Island, Khandwa, Madhya Pradesh 450554',
    youtubeSearchKeywords: 'Omkareshwar live darshan Narmada',
    latestVideoId: '',
    latestVideoTitle: 'Omkareshwar Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Omkareshwar_Temple.jpg/800px-Omkareshwar_Temple.jpg',
    latitude: 22.2456,
    longitude: 76.1510,
    description: 'Situated on Mandhata Island in the Narmada River, shaped like the holy Om symbol. A place of deep meditation and spiritual calm.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://omkareshwar.in/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 30, officialUrl: 'https://omkareshwar.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://omkareshwar.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://omkareshwar.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'kedarnath-jyotirlinga',
    templeName: 'Kedarnath Temple',
    hindiName: '\u0915\u0947\u0926\u093E\u0930\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Uttarakhand',
    city: 'Kedarnath',
    category: 'jyotirlinga',
    templeNumber: 5,
    significance: 'Highest Jyotirlinga in the Himalayas. Associated with Pandavas. Open only 6 months (Apr-Nov).',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Kedarnath, Rudraprayag, Uttarakhand 246445',
    youtubeSearchKeywords: 'Kedarnath live darshan 2026',
    latestVideoId: 'lvXLAcx9Xww',
    latestVideoTitle: 'Kedarnath Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://img.youtube.com/vi/lvXLAcx9Xww/maxresdefault.jpg',
    latitude: 30.7346,
    longitude: 79.0669,
    description: 'The highest of the 12 Jyotirlingas, nestled in the Garhwal Himalayas at 3,583m. Associated with the Pandavas. Accessible only 6 months a year.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Isha', startTime: '08:00 PM', duration: 20, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 5 }
  },
  {
    id: 'bhimashankar-jyotirlinga',
    templeName: 'Bhimashankar Temple',
    hindiName: '\u092D\u0940\u092E\u093E\u0936\u0902\u0915\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Maharashtra',
    city: 'Bhimashankar',
    category: 'jyotirlinga',
    templeNumber: 6,
    significance: 'Where Shiva killed demon Bhima. Located in dense Sahyadri forests. Biodiversity hotspot.',
    officialWebsite: 'https://bhimashankar.in/',
    website: 'https://bhimashankar.in/',
    address: 'Bhimashankar, Pune, Maharashtra 410509',
    youtubeSearchKeywords: 'Bhimashankar live darshan aarti',
    latestVideoId: '',
    latestVideoTitle: 'Bhimashankar Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Bhimashankar_temple_front.jpg/800px-Bhimashankar_temple_front.jpg',
    latitude: 19.0720,
    longitude: 73.5350,
    description: 'Located in the lush Sahyadri hills near Pune, where Lord Shiva defeated the demon Bhima. A biodiversity hotspot and spiritual retreat.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://bhimashankar.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://bhimashankar.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://bhimashankar.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://bhimashankar.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'kashi-vishwanath-jyotirlinga',
    templeName: 'Kashi Vishwanath Temple',
    hindiName: '\u0915\u093E\u0936\u0940 \u0935\u093F\u0936\u094D\u0935\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Uttar Pradesh',
    city: 'Varanasi',
    category: 'jyotirlinga',
    templeNumber: 7,
    significance: 'Center of the universe in Hindu belief. Grants moksha (liberation). Most visited Shiva temple.',
    officialWebsite: 'https://www.shrikashivishwanath.org/',
    website: 'https://www.shrikashivishwanath.org/',
    address: 'Lahori Tola, Varanasi, Domari, Uttar Pradesh 221001',
    phone: '+91-7080292930',
    youtubeSearchKeywords: 'Kashi Vishwanath live darshan aarti Varanasi',
    latestVideoId: 'yYc55IhPF3I',
    latestVideoTitle: 'Kashi Vishwanath Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/yYc55IhPF3I/maxresdefault.jpg',
    latitude: 25.3176,
    longitude: 83.0105,
    description: 'The most sacred Shiva temple in Varanasi, believed to be the center of the universe. One of the twelve Jyotirlingas, granting moksha to devotees.',
    aartiTimings: [
      { type: 'Mangala', startTime: '03:00 AM', duration: 60, officialUrl: 'https://www.shrikashivishwanath.org/' },
      { type: 'Shringar', startTime: '04:00 AM', duration: 45, officialUrl: 'https://www.shrikashivishwanath.org/' },
      { type: 'Bhog', startTime: '11:15 AM', duration: 65, officialUrl: 'https://www.shrikashivishwanath.org/' },
      { type: 'Sandhya', startTime: '07:00 PM', duration: 75, officialUrl: 'https://www.shrikashivishwanath.org/' },
      { type: 'Shringar', startTime: '09:00 PM', duration: 75, officialUrl: 'https://www.shrikashivishwanath.org/' },
      { type: 'Shayan', startTime: '10:30 PM', duration: 30, officialUrl: 'https://www.shrikashivishwanath.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '07:00 PM', hoursUntil: 2 }
  },
  {
    id: 'trimbakeshwar-jyotirlinga',
    templeName: 'Trimbakeshwar Temple',
    hindiName: '\u0924\u094D\u0930\u094D\u092F\u0902\u092C\u0915\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Maharashtra',
    city: 'Trimbak, Nashik',
    category: 'jyotirlinga',
    templeNumber: 8,
    significance: 'Three-faced lingam representing Brahma, Vishnu, Shiva. Origin of Godavari River.',
    officialWebsite: 'https://trimbakeshwar.org/',
    website: 'https://trimbakeshwar.org/',
    address: 'Trimbak, Nashik, Maharashtra 422212',
    youtubeSearchKeywords: 'Trimbakeshwar live darshan Godavari',
    latestVideoId: '',
    latestVideoTitle: 'Trimbakeshwar Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Trimbakeshwar_Temple%2C_Nashik.jpg/800px-Trimbakeshwar_Temple%2C_Nashik.jpg',
    latitude: 19.9320,
    longitude: 73.5307,
    description: 'Features a unique three-faced lingam representing the Hindu Trinity. The sacred Godavari River originates from the Kusavarta Kund within the temple complex.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:30 AM', duration: 30, officialUrl: 'https://trimbakeshwar.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://trimbakeshwar.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://trimbakeshwar.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://trimbakeshwar.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'baidyanath-jyotirlinga',
    templeName: 'Baidyanath Temple',
    hindiName: '\u092C\u0948\u0926\u094D\u092F\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Jharkhand',
    city: 'Deoghar',
    category: 'jyotirlinga',
    templeNumber: 9,
    significance: 'Associated with healing (Vaidya = healer). Sati\'s heart fell here - also a Shakti Peeth.',
    officialWebsite: 'https://baidyanathdham.in/',
    website: 'https://baidyanathdham.in/',
    address: 'Shivganga Muhalla, Deoghar, Jharkhand 814112',
    youtubeSearchKeywords: 'Baidyanath Deoghar live darshan aarti',
    latestVideoId: '',
    latestVideoTitle: 'Baidyanath Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7e/Baidyanath_Temple_Deoghar.jpg/800px-Baidyanath_Temple_Deoghar.jpg',
    latitude: 24.4820,
    longitude: 86.7000,
    description: 'Also known as Vaidyanath Dham, associated with healing. Sati\'s heart fell here, making it both a Jyotirlinga and a Shakti Peeth. Millions visit during Shravan.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://baidyanathdham.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://baidyanathdham.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://baidyanathdham.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://baidyanathdham.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'nageshwar-jyotirlinga',
    templeName: 'Nageshwar Temple',
    hindiName: '\u0928\u093E\u0917\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Gujarat',
    city: 'Dwarka',
    category: 'jyotirlinga',
    templeNumber: 10,
    significance: 'Symbolizes protection from all poisons. Features massive Shiva statue. Near Dwarka.',
    officialWebsite: 'https://nageshwar.org/',
    website: 'https://nageshwar.org/',
    address: 'Daarukavanam, Dwarka, Gujarat 361335',
    youtubeSearchKeywords: 'Nageshwar Dwarka live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Nageshwar Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Nageshwar_Temple.jpg/800px-Nageshwar_Temple.jpg',
    latitude: 22.3360,
    longitude: 69.0870,
    description: 'Represents protection from all poisons and negativity. Features a towering Shiva statue. Located near the sacred city of Dwarka.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://nageshwar.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://nageshwar.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://nageshwar.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://nageshwar.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'ramanathaswamy-jyotirlinga',
    templeName: 'Ramanathaswamy Temple',
    hindiName: '\u0930\u093E\u092E\u0928\u093E\u0925\u0938\u094D\u0935\u093E\u092E\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Tamil Nadu',
    city: 'Rameswaram',
    category: 'jyotirlinga',
    templeNumber: 11,
    significance: 'Established by Lord Rama. Also one of the 4 Char Dham. 22 holy theerthams.',
    officialWebsite: 'https://rameswaramramanathar.com/',
    website: 'https://rameswaramramanathar.com/',
    address: 'Rameswaram, Tamil Nadu 623526',
    youtubeSearchKeywords: 'Ramanathaswamy Rameswaram live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Ramanathaswamy Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ramanathaswamy_Temple%2C_Rameshwaram%2C_Tamil_Nadu.jpg/800px-Ramanathaswamy_Temple%2C_Rameshwaram%2C_Tamil_Nadu.jpg',
    latitude: 9.2881,
    longitude: 79.3174,
    description: 'Established by Lord Rama to seek forgiveness after defeating Ravana. Also one of the four Char Dham. Famous for its long corridors and 22 holy theerthams.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'grishneshwar-jyotirlinga',
    templeName: 'Grishneshwar Temple',
    hindiName: '\u0917\u0943\u0937\u094D\u0923\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Maharashtra',
    city: 'Ellora, Aurangabad',
    category: 'jyotirlinga',
    templeNumber: 12,
    significance: 'Last of 12 Jyotirlingas. Near UNESCO Ellora Caves. Smallest but deeply significant.',
    officialWebsite: 'https://grishneshwar.com/',
    website: 'https://grishneshwar.com/',
    address: 'Ghrishneshwar Temple Rd, Ellora, Verul, Maharashtra 431102',
    youtubeSearchKeywords: 'Grishneshwar Ellora live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Grishneshwar Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Grishneshwar_Temple.jpg/800px-Grishneshwar_Temple.jpg',
    latitude: 20.0240,
    longitude: 75.1700,
    description: 'The last of the 12 Jyotirlingas, located near the UNESCO World Heritage Ellora Caves. Associated with the devotion of Grusha.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:30 AM', duration: 30, officialUrl: 'https://grishneshwar.com/' },
      { type: 'Shringar', startTime: '07:30 AM', duration: 45, officialUrl: 'https://grishneshwar.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://grishneshwar.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://grishneshwar.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
];

// ===== 51 SHAKTI PEETHS (Major ones with streaming potential) =====
const shaktiPeeths: TempleStream[] = [
  {
    id: 'kamakhya-shakti-peeth',
    templeName: 'Kamakhya Temple',
    hindiName: '\u0915\u093E\u092E\u093E\u0916\u094D\u092F\u093E \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Assam',
    city: 'Guwahati',
    category: 'shakti-peeth',
    templeNumber: 1,
    significance: 'Sati\'s Yoni (genitals) fell here. Most powerful Tantric Shakti Peeth. Ambubachi Mela.',
    officialWebsite: 'https://kamakhya.org/',
    website: 'https://kamakhya.org/',
    address: 'Kamakhya, Nilachal Hill, Guwahati, Assam 781010',
    youtubeSearchKeywords: 'Kamakhya Temple live darshan Ambubachi',
    latestVideoId: 'Dasf8n5FeHs',
    latestVideoTitle: 'Kamakhya Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://img.youtube.com/vi/Dasf8n5FeHs/maxresdefault.jpg',
    latitude: 26.1665,
    longitude: 91.7055,
    description: 'The most powerful Tantric Shakti Peeth where Sati\'s Yoni fell. Located on Nilachal Hill, Guwahati. Famous for the annual Ambubachi Mela.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:30 AM', duration: 30, officialUrl: 'https://kamakhya.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://kamakhya.org/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://kamakhya.org/' },
      { type: 'Sandhya', startTime: '05:30 PM', duration: 30, officialUrl: 'https://kamakhya.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '05:30 PM', hoursUntil: 3 }
  },
  {
    id: 'vaishno-devi-shakti-peeth',
    templeName: 'Vaishno Devi Temple',
    hindiName: '\u0935\u0948\u0937\u094D\u0923\u094B \u0926\u0947\u0935\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Jammu & Kashmir',
    city: 'Katra',
    category: 'shakti-peeth',
    templeNumber: 2,
    significance: 'One of the holiest pilgrimage sites. Located on Trikuta Mountains. Millions visit annually.',
    officialWebsite: 'https://www.maavaishnodevi.org/',
    website: 'https://www.maavaishnodevi.org/',
    address: 'Vaishno Devi Shrine, Katra, Jammu & Kashmir 182144',
    phone: '+91-1991-232037',
    youtubeSearchKeywords: 'Vaishno Devi live darshan Katra',
    latestVideoId: '6nr2Nynv3JE',
    latestVideoTitle: 'Vaishno Devi Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/6nr2Nynv3JE/maxresdefault.jpg',
    latitude: 33.0300,
    longitude: 74.9490,
    description: 'One of the most visited temples in India, dedicated to Goddess Vaishno Devi. Located in the holy cave on Trikuta Mountains at 5,200 feet.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://www.maavaishnodevi.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://www.maavaishnodevi.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://www.maavaishnodevi.org/' },
      { type: 'Sandhya', startTime: '05:30 PM', duration: 30, officialUrl: 'https://www.maavaishnodevi.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '05:30 PM', hoursUntil: 3 }
  },
  {
    id: 'kalka-ji-shakti-peeth',
    templeName: 'Kalka Ji Temple',
    hindiName: '\u0915\u093E\u0932\u0915\u093E \u091C\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Delhi',
    city: 'New Delhi',
    category: 'shakti-peeth',
    templeNumber: 3,
    significance: 'Sati\'s right toes fell here. Major Devi temple in Delhi.',
    officialWebsite: 'https://kalkajimandir.com/',
    website: 'https://kalkajimandir.com/',
    address: 'Kalkaji, New Delhi, Delhi 110019',
    youtubeSearchKeywords: 'Kalka Ji live darshan Delhi',
    latestVideoId: '',
    latestVideoTitle: 'Kalka Ji Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Kalkaji-shrine.jpg/800px-Kalkaji-shrine.jpg',
    latitude: 28.5500,
    longitude: 77.2600,
    description: 'An ancient Hindu temple dedicated to Goddess Kali, believed to be where Sati\'s right toes fell. One of Delhi\'s most visited temples.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://kalkajimandir.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://kalkajimandir.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://kalkajimandir.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://kalkajimandir.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'jwala-devi-shakti-peeth',
    templeName: 'Jwala Devi Temple',
    hindiName: '\u091C\u094D\u0935\u093E\u0932\u093E \u0926\u0947\u0935\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Himachal Pradesh',
    city: 'Kangra',
    category: 'shakti-peeth',
    templeNumber: 4,
    significance: 'Sati\'s tongue fell here. Eternal flame burns without fuel.',
    officialWebsite: 'https://jwalamukhi.org/',
    website: 'https://jwalamukhi.org/',
    address: 'Jwalamukhi, Kangra, Himachal Pradesh 176031',
    youtubeSearchKeywords: 'Jwala Devi Kangra live darshan eternal flame',
    latestVideoId: '',
    latestVideoTitle: 'Jwala Devi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Jwala_Devi_Temple_%28NEW%29.jpg/800px-Jwala_Devi_Temple_%28NEW%29.jpg',
    latitude: 31.8800,
    longitude: 76.3200,
    description: 'Famous for its eternal flame that burns without any fuel. Believed to be where Sati\'s tongue fell. A marvel of nature and faith.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://jwalamukhi.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://jwalamukhi.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://jwalamukhi.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://jwalamukhi.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'ambaji-shakti-peeth',
    templeName: 'Ambaji Temple',
    hindiName: '\u0905\u0902\u092C\u093E\u091C\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Gujarat',
    city: 'Ambaji',
    category: 'shakti-peeth',
    templeNumber: 5,
    significance: 'Sati\'s heart fell here. One of 51 original Shakti Peeths. No idol - only Shri Yantra.',
    officialWebsite: 'https://ambaji.com/',
    website: 'https://ambaji.com/',
    address: 'Ambaji, Banaskantha, Gujarat 385110',
    youtubeSearchKeywords: 'Ambaji live darshan Gujarat',
    latestVideoId: '',
    latestVideoTitle: 'Ambaji Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Ambaji_Temple.jpg/800px-Ambaji_Temple.jpg',
    latitude: 24.3330,
    longitude: 72.8500,
    description: 'One of the 51 original Shakti Peeths where Sati\'s heart fell. Unique - no idol, only a sacred Shri Yantra is worshipped.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://ambaji.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://ambaji.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://ambaji.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://ambaji.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'tarapith-shakti-peeth',
    templeName: 'Tara Devi Temple',
    hindiName: '\u0924\u093E\u0930\u093E \u0926\u0947\u0935\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'West Bengal',
    city: 'Tarapith',
    category: 'shakti-peeth',
    templeNumber: 6,
    significance: 'Sati\'s third eye fell here. Famous for Tantric practices and cremation ground sadhana.',
    officialWebsite: 'https://tarapith.org/',
    website: 'https://tarapith.org/',
    address: 'Tarapith, Birbhum, West Bengal 731233',
    youtubeSearchKeywords: 'Tarapith live darshan aarti',
    latestVideoId: '',
    latestVideoTitle: 'Tarapith Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tarapith_Kali_temple_at_Tarapith_03.jpg/800px-Tarapith_Kali_temple_at_Tarapith_03.jpg',
    latitude: 24.1100,
    longitude: 87.7900,
    description: 'Where Sati\'s third eye fell. A major center of Tantric worship, famous for its cremation ground (smashana) rituals.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://tarapith.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://tarapith.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://tarapith.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://tarapith.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'dakshineswar-shakti-peeth',
    templeName: 'Dakshineswar Kali Temple',
    hindiName: '\u0926\u0915\u094D\u0937\u093F\u0923\u0947\u0936\u094D\u0935\u0930 \u0915\u093E\u0932\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'West Bengal',
    city: 'Kolkata',
    category: 'shakti-peeth',
    templeNumber: 7,
    significance: 'Where Sati\'s right toes fell. Sri Ramakrishna Paramahamsa was head priest here.',
    officialWebsite: 'https://dakshineswarkalitemple.org/',
    website: 'https://dakshineswarkalitemple.org/',
    address: 'Dakshineswar, Kolkata, West Bengal 700076',
    youtubeSearchKeywords: 'Dakshineswar Kali live darshan Kolkata',
    latestVideoId: '',
    latestVideoTitle: 'Dakshineswar Kali Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Dakshineswar_Kali_Temple.jpg/800px-Dakshineswar_Kali_Temple.jpg',
    latitude: 22.6540,
    longitude: 88.3580,
    description: 'Famous as the spiritual center of Sri Ramakrishna Paramahamsa. Located on the banks of the Hooghly River.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://dakshineswarkalitemple.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://dakshineswarkalitemple.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://dakshineswarkalitemple.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://dakshineswarkalitemple.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'chamundeshwari-shakti-peeth',
    templeName: 'Chamundeshwari Temple',
    hindiName: '\u091A\u093E\u092E\u0941\u0902\u0921\u0947\u0936\u094D\u0935\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Karnataka',
    city: 'Mysuru',
    category: 'shakti-peeth',
    templeNumber: 8,
    significance: 'Sati\'s hair fell here. Located on Chamundi Hills. Mysuru Dasara center.',
    officialWebsite: 'https://chamundeshwaritemple.in/',
    website: 'https://chamundeshwaritemple.in/',
    address: 'Chamundi Hill, Mysuru, Karnataka 570010',
    youtubeSearchKeywords: 'Chamundeshwari Mysuru live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Chamundeshwari Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Chamundeshwari_Temple.jpg/800px-Chamundeshwari_Temple.jpg',
    latitude: 12.2720,
    longitude: 76.6700,
    description: 'Located atop Chamundi Hills, where Sati\'s hair fell. The spiritual center of Mysuru Dasara celebrations.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://chamundeshwaritemple.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://chamundeshwaritemple.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://chamundeshwaritemple.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://chamundeshwaritemple.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'mahalakshmi-shakti-peeth',
    templeName: 'Mahalakshmi Temple',
    hindiName: '\u092E\u0939\u093E\u0932\u0915\u094D\u0937\u094D\u092E\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Maharashtra',
    city: 'Kolhapur',
    category: 'shakti-peeth',
    templeNumber: 9,
    significance: 'Sati\'s eyes fell here. One of the most powerful Devi temples in Maharashtra.',
    officialWebsite: 'https://mahalaxmikolhapur.com/',
    website: 'https://mahalaxmikolhapur.com/',
    address: 'Mahalaxmi Temple, Kolhapur, Maharashtra 416012',
    youtubeSearchKeywords: 'Mahalakshmi Kolhapur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Mahalakshmi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Mahalakshmi_temple%2C_Kolhapur.jpg/800px-Mahalakshmi_temple%2C_Kolhapur.jpg',
    latitude: 16.7000,
    longitude: 74.2300,
    description: 'One of the six abodes of Shakti (Shakti Peethas) where Sati\'s eyes fell. The deity faces west, a unique feature.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://mahalaxmikolhapur.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://mahalaxmikolhapur.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://mahalaxmikolhapur.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://mahalaxmikolhapur.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'tulja-bhavani-shakti-peeth',
    templeName: 'Tulja Bhavani Temple',
    hindiName: '\u0924\u0941\u0932\u091C\u093E \u092D\u0935\u093E\u0928\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Maharashtra',
    city: 'Tuljapur',
    category: 'shakti-peeth',
    templeNumber: 10,
    significance: 'Sati\'s left arm fell here. Kuldevi of Shivaji Maharaj.',
    officialWebsite: 'https://tuljabhavani.in/',
    website: 'https://tuljabhavani.in/',
    address: 'Tuljapur, Osmanabad, Maharashtra 413601',
    youtubeSearchKeywords: 'Tulja Bhavani Tuljapur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Tulja Bhavani Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tulja_Bhavani_Temple_2026_%281%29.jpg/800px-Tulja_Bhavani_Temple_2026_%281%29.jpg',
    latitude: 18.0100,
    longitude: 76.0800,
    description: 'The family deity (Kuldevi) of Chhatrapati Shivaji Maharaj. Where Sati\'s left arm fell. A symbol of strength and protection.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://tuljabhavani.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://tuljabhavani.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://tuljabhavani.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://tuljabhavani.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'renuka-devi-shakti-peeth',
    templeName: 'Renuka Devi Temple',
    hindiName: '\u0930\u0947\u0923\u0941\u0915\u093E \u0926\u0947\u0935\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Maharashtra',
    city: 'Mahur',
    category: 'shakti-peeth',
    templeNumber: 11,
    significance: 'Sati\'s neck fell here. One of three and a half Shakti Peeths in Maharashtra.',
    officialWebsite: 'https://renukadevi.com/',
    website: 'https://renukadevi.com/',
    address: 'Mahur, Nanded, Maharashtra 431805',
    youtubeSearchKeywords: 'Renuka Devi Mahur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Renuka Devi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Renukadevi_Temple_at_Mahur_Village.jpg/800px-Renukadevi_Temple_at_Mahur_Village.jpg',
    latitude: 19.8500,
    longitude: 77.9300,
    description: 'Where Sati\'s neck fell. One of the three and a half Shakti Peeths in Maharashtra. A serene and powerful spiritual center.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://renukadevi.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://renukadevi.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://renukadevi.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://renukadevi.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'saptashrungi-shakti-peeth',
    templeName: 'Saptashrungi Devi Temple',
    hindiName: '\u0938\u092A\u094D\u0924\u0936\u0943\u0902\u0917\u0940 \u0926\u0947\u0935\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Maharashtra',
    city: 'Vani, Nashik',
    category: 'shakti-peeth',
    templeNumber: 12,
    significance: 'Sati\'s right arm fell here. Located among seven peaks.',
    officialWebsite: 'https://saptashrungi.org/',
    website: 'https://saptashrungi.org/',
    address: 'Saptashrungi Gad, Vani, Nashik, Maharashtra 422215',
    youtubeSearchKeywords: 'Saptashrungi Vani live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Saptashrungi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Goddess_Saptashrungi_Devi_Temple1.jpg/800px-Goddess_Saptashrungi_Devi_Temple1.jpg',
    latitude: 20.0300,
    longitude: 73.5600,
    description: 'Located among seven mountain peaks (Sapta = seven, Shrungi = peaks). Where Sati\'s right arm fell.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://saptashrungi.org/' },
      { type: 'Shringar', startTime: '07:30 AM', duration: 45, officialUrl: 'https://saptashrungi.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://saptashrungi.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://saptashrungi.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'vishalakshi-shakti-peeth',
    templeName: 'Vishalakshi Temple',
    hindiName: '\u0935\u093F\u0936\u093E\u0932\u093E\u0915\u094D\u0937\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Uttar Pradesh',
    city: 'Varanasi',
    category: 'shakti-peeth',
    templeNumber: 13,
    significance: 'Sati\'s earrings fell here. Companion temple to Kashi Vishwanath.',
    officialWebsite: 'https://vishalakshitemple.com/',
    website: 'https://vishalakshitemple.com/',
    address: 'Varanasi, Uttar Pradesh 221001',
    youtubeSearchKeywords: 'Vishalakshi Varanasi live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Vishalakshi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Vishalakshi_Temple.jpg/800px-Vishalakshi_Temple.jpg',
    latitude: 25.3100,
    longitude: 83.0100,
    description: 'Where Sati\'s earrings (kundal) fell. Located near Kashi Vishwanath, representing the divine feminine aspect of Varanasi.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://vishalakshitemple.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://vishalakshitemple.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://vishalakshitemple.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://vishalakshitemple.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'biraja-shakti-peeth',
    templeName: 'Biraja Temple',
    hindiName: '\u092C\u093F\u0930\u091C\u093E \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Odisha',
    city: 'Jajpur',
    category: 'shakti-peeth',
    templeNumber: 14,
    significance: 'Sati\'s navel fell here. Also known as Viraja Kshetra.',
    officialWebsite: 'https://birajatemple.com/',
    website: 'https://birajatemple.com/',
    address: 'Jajpur, Odisha 755001',
    youtubeSearchKeywords: 'Biraja Jajpur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Biraja Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Biraja_Temple.jpg/800px-Biraja_Temple.jpg',
    latitude: 20.8500,
    longitude: 86.3300,
    description: 'Where Sati\'s navel fell. Also known as Viraja Kshetra. An ancient temple with deep spiritual significance in Odisha.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://birajatemple.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://birajatemple.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://birajatemple.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://birajatemple.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'purnagiri-shakti-peeth',
    templeName: 'Purnagiri Temple',
    hindiName: '\u092A\u0942\u0930\u094D\u0923\u093E\u0917\u093F\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Uttarakhand',
    city: 'Tanakpur',
    category: 'shakti-peeth',
    templeNumber: 15,
    significance: 'Sati\'s navel fell here. Located on a hilltop with panoramic views.',
    officialWebsite: 'https://purnagiri.com/',
    website: 'https://purnagiri.com/',
    address: 'Purnagiri, Tanakpur, Champawat, Uttarakhand 262310',
    youtubeSearchKeywords: 'Purnagiri Tanakpur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Purnagiri Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Purnagiri_Temple.jpg/800px-Purnagiri_Temple.jpg',
    latitude: 29.0700,
    longitude: 80.1000,
    description: 'Where Sati\'s navel fell. Located on a hilltop near Tanakpur with breathtaking Himalayan views.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://purnagiri.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://purnagiri.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://purnagiri.com/' },
      { type: 'Sandhya', startTime: '05:30 PM', duration: 30, officialUrl: 'https://purnagiri.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '05:30 PM', hoursUntil: 3 }
  },
  {
    id: 'vindhyavasini-shakti-peeth',
    templeName: 'Vindhyavasini Temple',
    hindiName: '\u0935\u093F\u0902\u0927\u094D\u092F\u0935\u093E\u0938\u093F\u0928\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Uttar Pradesh',
    city: 'Mirzapur',
    category: 'shakti-peeth',
    templeNumber: 16,
    significance: 'Sati\'s knees fell here. Worshipped for family blessings and strength.',
    officialWebsite: 'https://vindhyachal.com/',
    website: 'https://vindhyachal.com/',
    address: 'Vindhyachal, Mirzapur, Uttar Pradesh 231307',
    youtubeSearchKeywords: 'Vindhyavasini Mirzapur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Vindhyavasini Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Maa_Vindhyavasini_temple%2C_Vindhyachal.jpg/800px-Maa_Vindhyavasini_temple%2C_Vindhyachal.jpg',
    latitude: 25.1600,
    longitude: 82.5000,
    description: 'Where Sati\'s knees fell. Located in the Vindhya mountain range. Worshipped for family well-being and strength.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://vindhyachal.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://vindhyachal.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://vindhyachal.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://vindhyachal.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'jogulamba-shakti-peeth',
    templeName: 'Jogulamba Temple',
    hindiName: '\u091C\u094B\u0917\u0941\u0932\u0902\u092C\u093E \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Telangana',
    city: 'Alampur',
    category: 'shakti-peeth',
    templeNumber: 17,
    significance: 'Sati\'s upper teeth fell here. One of the 18 Maha Shakti Peethas.',
    officialWebsite: 'https://jogulamba.com/',
    website: 'https://jogulamba.com/',
    address: 'Alampur, Jogulamba Gadwal, Telangana 509152',
    youtubeSearchKeywords: 'Jogulamba Alampur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Jogulamba Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Jogulamba_temple_.jpg/800px-Jogulamba_temple_.jpg',
    latitude: 15.8800,
    longitude: 78.1400,
    description: 'One of the 18 Maha Shakti Peethas where Sati\'s upper teeth fell. Located on the banks of Tungabhadra River.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://jogulamba.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://jogulamba.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://jogulamba.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://jogulamba.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'manibandh-shakti-peeth',
    templeName: 'Manibandh Temple',
    hindiName: '\u092E\u0923\u093F\u092C\u0902\u0927 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Rajasthan',
    city: 'Pushkar',
    category: 'shakti-peeth',
    templeNumber: 18,
    significance: 'Sati\'s wrists fell here. Located near the sacred Pushkar Lake.',
    officialWebsite: 'https://pushkar.com/',
    website: 'https://pushkar.com/',
    address: 'Pushkar, Ajmer, Rajasthan 305022',
    youtubeSearchKeywords: 'Pushkar Manibandh live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Manibandh Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Pushkar_Temple.jpg/800px-Pushkar_Temple.jpg',
    latitude: 26.4870,
    longitude: 74.5500,
    description: 'Where Sati\'s wrists fell. Located in the holy town of Pushkar near the sacred lake.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://pushkar.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://pushkar.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://pushkar.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://pushkar.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'mangalagauri-shakti-peeth',
    templeName: 'Mangalagauri Temple',
    hindiName: '\u092E\u0902\u0917\u0932\u093E\u0917\u094C\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Bihar',
    city: 'Gaya',
    category: 'shakti-peeth',
    templeNumber: 19,
    significance: 'Sati\'s breast fell here. Known for motherly love and blessings.',
    officialWebsite: 'https://mangalagauri.com/',
    website: 'https://mangalagauri.com/',
    address: 'Mangalagauri, Gaya, Bihar 823001',
    youtubeSearchKeywords: 'Mangalagauri Gaya live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Mangalagauri Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Mangalagauri_Temple.jpg/800px-Mangalagauri_Temple.jpg',
    latitude: 24.7900,
    longitude: 85.0000,
    description: 'Where Sati\'s breast fell. Known for motherly love and blessings. An important temple in the holy city of Gaya.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://mangalagauri.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://mangalagauri.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://mangalagauri.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://mangalagauri.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'tripura-sundari-shakti-peeth',
    templeName: 'Tripura Sundari Temple',
    hindiName: '\u0924\u094D\u0930\u093F\u092A\u0941\u0930\u093E \u0938\u0941\u0902\u0926\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Tripura',
    city: 'Udaipur',
    category: 'shakti-peeth',
    templeNumber: 20,
    significance: 'Sati\'s right foot fell here. One of the 51 Shakti Peeths.',
    officialWebsite: 'https://tripurasundari.org/',
    website: 'https://tripurasundari.org/',
    address: 'Udaipur, Gomati, Tripura 799013',
    youtubeSearchKeywords: 'Tripura Sundari Udaipur live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Tripura Sundari Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Tripura_Sundari_Temple.jpg/800px-Tripura_Sundari_Temple.jpg',
    latitude: 23.5300,
    longitude: 91.4800,
    description: 'Where Sati\'s right foot fell. One of the 51 Shakti Peeths, located in Udaipur, Tripura.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://tripurasundari.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://tripurasundari.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://tripurasundari.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://tripurasundari.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
];

// ===== CHAR DHAM (4 DHAM by Adi Shankaracharya) =====
const charDham: TempleStream[] = [
  {
    id: 'badrinath-char-dham',
    templeName: 'Badrinath Temple',
    hindiName: '\u092C\u0926\u094D\u0930\u0940\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Uttarakhand',
    city: 'Badrinath',
    category: 'char-dham',
    templeNumber: 1,
    significance: 'One of 4 Char Dham. Dham of Satyuga. Dedicated to Lord Badri Vishal.',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Badrinath, Chamoli, Uttarakhand 246422',
    youtubeSearchKeywords: 'Badrinath live darshan aarti',
    latestVideoId: '',
    latestVideoTitle: 'Badrinath Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Badrinath_temple_%281%29.jpg/800px-Badrinath_temple_%281%29.jpg',
    latitude: 30.7433,
    longitude: 79.4938,
    description: 'One of the four Char Dham pilgrimage sites established by Adi Shankaracharya. Dedicated to Lord Badri Vishal (Vishnu). Located on the banks of Alaknanda River.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'dwarka-char-dham',
    templeName: 'Dwarkadhish Temple',
    hindiName: '\u0926\u094D\u0935\u093E\u0930\u0915\u093E\u0927\u0940\u0936 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Gujarat',
    city: 'Dwarka',
    category: 'char-dham',
    templeNumber: 2,
    significance: 'One of 4 Char Dham. Dham of Dwaparayuga. Krishna\'s kingdom.',
    officialWebsite: 'https://dwarkadhish.org/',
    website: 'https://dwarkadhish.org/',
    address: 'Dwarka, Devbhoomi Dwarka, Gujarat 361335',
    youtubeSearchKeywords: 'Dwarkadhish live darshan aarti',
    latestVideoId: 'VR1BPJkniOA',
    latestVideoTitle: 'Dwarkadhish Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://img.youtube.com/vi/VR1BPJkniOA/maxresdefault.jpg',
    latitude: 22.2376,
    longitude: 68.9674,
    description: 'The legendary kingdom of Lord Krishna. One of the four Char Dham pilgrimage sites. A magnificent temple on the coast of Gujarat.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://dwarkadhish.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://dwarkadhish.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://dwarkadhish.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://dwarkadhish.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'jagannath-char-dham',
    templeName: 'Jagannath Temple',
    hindiName: '\u091C\u0917\u0928\u094D\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Odisha',
    city: 'Puri',
    category: 'char-dham',
    templeNumber: 3,
    significance: 'One of 4 Char Dham. Dham of Kaliyuga. Famous for Rath Yatra.',
    officialWebsite: 'https://shreejagannatha.in/',
    website: 'https://shreejagannatha.in/',
    address: 'Jagannath Temple Road, Puri, Odisha 752001',
    youtubeSearchKeywords: 'Jagannath Puri live darshan Rath Yatra',
    latestVideoId: '',
    latestVideoTitle: 'Jagannath Puri Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Jagannath_Temple_Puri.jpg/800px-Jagannath_Temple_Puri.jpg',
    latitude: 19.8047,
    longitude: 85.8312,
    description: 'One of the four Char Dham and one of the four holy pilgrimage sites. Famous for the annual Rath Yatra. Home to Lord Jagannath, Balabhadra, and Subhadra.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://shreejagannatha.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://shreejagannatha.in/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://shreejagannatha.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://shreejagannatha.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'rameshwaram-char-dham',
    templeName: 'Ramanathaswamy Temple',
    hindiName: '\u0930\u093E\u092E\u0947\u0936\u094D\u0935\u0930\u092E \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Tamil Nadu',
    city: 'Rameswaram',
    category: 'char-dham',
    templeNumber: 4,
    significance: 'One of 4 Char Dham. Dham of Tretayuga. Also 11th Jyotirlinga.',
    officialWebsite: 'https://rameswaramramanathar.com/',
    website: 'https://rameswaramramanathar.com/',
    address: 'Rameswaram, Tamil Nadu 623526',
    youtubeSearchKeywords: 'Rameshwaram live darshan Char Dham',
    latestVideoId: '',
    latestVideoTitle: 'Rameshwaram Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Ramanathaswamy_Temple%2C_Rameshwaram%2C_Tamil_Nadu.jpg/800px-Ramanathaswamy_Temple%2C_Rameshwaram%2C_Tamil_Nadu.jpg',
    latitude: 9.2881,
    longitude: 79.3174,
    description: 'One of the four Char Dham pilgrimage sites. Also the 11th Jyotirlinga. Established by Lord Rama. Famous for its 22 holy theerthams.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://rameswaramramanathar.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
];

// ===== CHOTA CHAR DHAM (Uttarakhand) =====
const chotaCharDham: TempleStream[] = [
  {
    id: 'yamunotri-chota-char-dham',
    templeName: 'Yamunotri Temple',
    hindiName: '\u092F\u092E\u0941\u0928\u094B\u0924\u094D\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Uttarakhand',
    city: 'Yamunotri',
    category: 'chota-char-dham',
    templeNumber: 1,
    significance: 'Source of Yamuna River. First temple in Chota Char Dham circuit.',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Yamunotri, Uttarkashi, Uttarakhand 249193',
    youtubeSearchKeywords: 'Yamunotri live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Yamunotri Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Yamunotri_Temple.jpg/800px-Yamunotri_Temple.jpg',
    latitude: 31.0140,
    longitude: 78.4600,
    description: 'The source of the Yamuna River and the first temple in the Chota Char Dham pilgrimage circuit. Located at 3,293 meters in the Garhwal Himalayas.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'gangotri-chota-char-dham',
    templeName: 'Gangotri Temple',
    hindiName: '\u0917\u0902\u0917\u094B\u0924\u094D\u0930\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Uttarakhand',
    city: 'Gangotri',
    category: 'chota-char-dham',
    templeNumber: 2,
    significance: 'Source of Ganga River. Second temple in Chota Char Dham circuit.',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Gangotri, Uttarkashi, Uttarakhand 249135',
    youtubeSearchKeywords: 'Gangotri live darshan Ganga',
    latestVideoId: '',
    latestVideoTitle: 'Gangotri Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Gangotri_temple.jpg/800px-Gangotri_temple.jpg',
    latitude: 30.9947,
    longitude: 78.9412,
    description: 'The source of the holy Ganga River. The second temple in the Chota Char Dham circuit. Located at 3,100 meters in the Himalayas.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'kedarnath-chota-char-dham',
    templeName: 'Kedarnath Temple',
    hindiName: '\u0915\u0947\u0926\u093E\u0930\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Shiva',
    state: 'Uttarakhand',
    city: 'Kedarnath',
    category: 'chota-char-dham',
    templeNumber: 3,
    significance: 'Third temple in Chota Char Dham. Also 5th Jyotirlinga.',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Kedarnath, Rudraprayag, Uttarakhand 246445',
    youtubeSearchKeywords: 'Kedarnath live darshan',
    latestVideoId: 'lvXLAcx9Xww',
    latestVideoTitle: 'Kedarnath Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://img.youtube.com/vi/lvXLAcx9Xww/maxresdefault.jpg',
    latitude: 30.7346,
    longitude: 79.0669,
    description: 'The third temple in the Chota Char Dham circuit and the 5th Jyotirlinga. Located at 3,583 meters in the Garhwal Himalayas.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'badrinath-chota-char-dham',
    templeName: 'Badrinath Temple',
    hindiName: '\u092C\u0926\u094D\u0930\u0940\u0928\u093E\u0925 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Uttarakhand',
    city: 'Badrinath',
    category: 'chota-char-dham',
    templeNumber: 4,
    significance: 'Fourth temple in Chota Char Dham. Also 1st Char Dham.',
    officialWebsite: 'https://badrinath-kedarnath.gov.in/',
    website: 'https://badrinath-kedarnath.gov.in/',
    address: 'Badrinath, Chamoli, Uttarakhand 246422',
    youtubeSearchKeywords: 'Badrinath live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Badrinath Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Badrinath_temple_%281%29.jpg/800px-Badrinath_temple_%281%29.jpg',
    latitude: 30.7433,
    longitude: 79.4938,
    description: 'The fourth and final temple in the Chota Char Dham circuit. Also one of the four Char Dham pilgrimage sites. Dedicated to Lord Badri Vishal.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://badrinath-kedarnath.gov.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
];

// ===== OTHER MAJOR TEMPLES =====
const majorTemples: TempleStream[] = [
  {
    id: 'tirupati-balaji',
    templeName: 'Sri Venkateswara Temple',
    hindiName: '\u0936\u094D\u0930\u0940 \u0935\u0947\u0902\u0915\u091F\u0947\u0936\u094D\u0935\u0930 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Andhra Pradesh',
    city: 'Tirupati',
    category: 'major',
    significance: 'Most visited temple in India. Richest temple in the world.',
    officialWebsite: 'https://www.tirumala.org/',
    website: 'https://www.tirumala.org/',
    address: 'Sri Venkateswara Temple, Tirumala, Tirupati, Andhra Pradesh 517507',
    phone: '+91-877-2263655',
    youtubeSearchKeywords: 'Tirumala Tirupati live darshan TTD',
    latestVideoId: 'eTWaPQW7rdk',
    latestVideoTitle: 'Tirupati Balaji Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/eTWaPQW7rdk/maxresdefault.jpg',
    latitude: 13.6833,
    longitude: 79.3500,
    description: 'The most visited temple in India and one of the richest religious institutions in the world. Dedicated to Lord Venkateswara (Balaji) on the Tirumala hills.',
    aartiTimings: [
      { type: 'Mangala', startTime: '03:30 AM', duration: 30, officialUrl: 'https://www.tirumala.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://www.tirumala.org/' },
      { type: 'Bhog', startTime: '12:30 PM', duration: 30, officialUrl: 'https://www.tirumala.org/' },
      { type: 'Sandhya', startTime: '06:30 PM', duration: 30, officialUrl: 'https://www.tirumala.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:30 PM', hoursUntil: 3 }
  },
  {
    id: 'ayodhya-ram-mandir',
    templeName: 'Shri Ram Janmabhoomi Temple',
    hindiName: '\u0936\u094D\u0930\u0940 \u0930\u093E\u092E \u091C\u0928\u094D\u092E\u092D\u0942\u092E\u093F \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Uttar Pradesh',
    city: 'Ayodhya',
    category: 'major',
    significance: 'Birthplace of Lord Ram. Newly reconstructed grand temple.',
    officialWebsite: 'https://srjbtkshetra.org/',
    website: 'https://srjbtkshetra.org/',
    address: 'Ram Janmabhoomi, Ayodhya, Uttar Pradesh 224123',
    youtubeSearchKeywords: 'Ayodhya Ram Mandir live darshan',
    latestVideoId: '-9Zbxhxv7Zs',
    latestVideoTitle: 'Ram Mandir Ayodhya Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/-9Zbxhxv7Zs/maxresdefault.jpg',
    latitude: 26.7956,
    longitude: 82.1943,
    description: 'The sacred birthplace of Lord Ram. The newly constructed grand temple is a symbol of faith and cultural heritage for millions of Hindus worldwide.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://srjbtkshetra.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://srjbtkshetra.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://srjbtkshetra.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://srjbtkshetra.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'siddhivinayak',
    templeName: 'Siddhivinayak Temple',
    hindiName: '\u0938\u093F\u0926\u094D\u0927\u093F\u0935\u093F\u0928\u093E\u092F\u0915 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Ganesha',
    state: 'Maharashtra',
    city: 'Mumbai',
    category: 'major',
    significance: 'Most famous Ganesha temple in Mumbai. Grants all siddhis (powers).',
    officialWebsite: 'https://www.siddhivinayak.org/',
    website: 'https://www.siddhivinayak.org/',
    address: 'Prabhat Road, Prabhadevi, Mumbai, Maharashtra 400025',
    phone: '+91-22-24224455',
    youtubeSearchKeywords: 'Siddhivinayak Mumbai live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Siddhivinayak Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Siddhivinayak_Temple.jpg/800px-Siddhivinayak_Temple.jpg',
    latitude: 19.0176,
    longitude: 72.8292,
    description: 'One of the most famous and richest Ganesha temples in India. Known for granting all siddhis (spiritual powers) to devotees.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:30 AM', duration: 30, officialUrl: 'https://www.siddhivinayak.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://www.siddhivinayak.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://www.siddhivinayak.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://www.siddhivinayak.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'golden-temple',
    templeName: 'Golden Temple',
    hindiName: '\u0938\u094D\u0935\u0930\u094D\u0923 \u092E\u0902\u0926\u093F\u0930',
    deity: 'All',
    state: 'Punjab',
    city: 'Amritsar',
    category: 'major',
    significance: 'Holiest Gurdwara of Sikhism. Symbol of equality and divine grace.',
    officialWebsite: 'https://sgpc.net/',
    website: 'https://sgpc.net/',
    address: 'Golden Temple, Amritsar, Punjab 143006',
    youtubeSearchKeywords: 'Golden Temple Amritsar live kirtan',
    latestVideoId: 'py2EAuU7Sw0',
    latestVideoTitle: 'Golden Temple Live Kirtan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/py2EAuU7Sw0/maxresdefault.jpg',
    latitude: 31.6200,
    longitude: 74.8765,
    description: 'The holiest Gurdwara and the most sacred place of worship for the Sikh religion. A symbol of human brotherhood and equality.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://sgpc.net/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://sgpc.net/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://sgpc.net/' },
      { type: 'Sandhya', startTime: '04:30 PM', duration: 30, officialUrl: 'https://sgpc.net/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '04:30 PM', hoursUntil: 2 }
  },
  {
    id: 'meenakshi-temple',
    templeName: 'Meenakshi Amman Temple',
    hindiName: '\u092E\u0940\u0928\u093E\u0915\u094D\u0937\u0940 \u0905\u092E\u094D\u092E\u0928 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Devi',
    state: 'Tamil Nadu',
    city: 'Madurai',
    category: 'major',
    significance: 'One of the oldest and largest temples in India. Architectural marvel.',
    officialWebsite: 'https://www.maduraimeenakshi.org/',
    website: 'https://www.maduraimeenakshi.org/',
    address: 'Meenakshi Amman Temple, Madurai, Tamil Nadu 625001',
    youtubeSearchKeywords: 'Meenakshi Madurai live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Meenakshi Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Meenakshi_Temple.jpg/800px-Meenakshi_Temple.jpg',
    latitude: 9.9252,
    longitude: 78.1198,
    description: 'One of the oldest and largest temple complexes in India. Famous for its stunning architecture, 14 gopurams, and the Hall of Thousand Pillars.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:00 AM', duration: 30, officialUrl: 'https://www.maduraimeenakshi.org/' },
      { type: 'Shringar', startTime: '08:00 AM', duration: 45, officialUrl: 'https://www.maduraimeenakshi.org/' },
      { type: 'Bhog', startTime: '01:00 PM', duration: 30, officialUrl: 'https://www.maduraimeenakshi.org/' },
      { type: 'Sandhya', startTime: '05:00 PM', duration: 30, officialUrl: 'https://www.maduraimeenakshi.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '05:00 PM', hoursUntil: 3 }
  },
  {
    id: 'shirdi-sai-baba',
    templeName: 'Shirdi Sai Baba Temple',
    hindiName: '\u0936\u093F\u0930\u094D\u0921\u0940 \u0938\u093E\u0908\u0902 \u092C\u093E\u092C\u093E \u092E\u0902\u0926\u093F\u0930',
    deity: 'All',
    state: 'Maharashtra',
    city: 'Shirdi',
    category: 'major',
    significance: 'Samadhi of Sai Baba. Millions visit for blessings.',
    officialWebsite: 'https://sai.org.in/',
    website: 'https://sai.org.in/',
    address: 'Shirdi, Ahmednagar, Maharashtra 423109',
    phone: '+91-2423-258685',
    youtubeSearchKeywords: 'Shirdi Sai Baba live darshan',
    latestVideoId: 'Ffj-Xn6Xqnc',
    latestVideoTitle: 'Shirdi Sai Baba Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/Ffj-Xn6Xqnc/maxresdefault.jpg',
    latitude: 19.7600,
    longitude: 74.4400,
    description: 'The sacred Samadhi temple of Sai Baba, one of India\'s most revered saints. Millions of devotees visit Shirdi seeking blessings and peace.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://sai.org.in/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://sai.org.in/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://sai.org.in/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://sai.org.in/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'iskcon-bangalore',
    templeName: 'ISKCON Bangalore',
    hindiName: '\u0907\u0938\u094D\u0915\u0949\u0928 \u092C\u0948\u0902\u0917\u0932\u094B\u0930',
    deity: 'Vishnu',
    state: 'Karnataka',
    city: 'Bengaluru',
    category: 'major',
    significance: 'One of the largest ISKCON temples in the world. Beautiful architecture.',
    officialWebsite: 'https://iskconbangalore.org/',
    website: 'https://iskconbangalore.org/',
    address: 'Hare Krishna Hill, Bengaluru, Karnataka 560010',
    youtubeSearchKeywords: 'ISKCON Bangalore live darshan',
    latestVideoId: 'em-v1WZYggk',
    latestVideoTitle: 'ISKCON Bangalore Live Darshan',
    isLive: true,
    streamType: 'live',
    lastRefreshed: now,
    refreshInterval: 15,
    imageUrl: 'https://img.youtube.com/vi/em-v1WZYggk/maxresdefault.jpg',
    latitude: 13.0100,
    longitude: 77.5500,
    description: 'One of the largest ISKCON temples in the world. Known for its stunning neo-classical architecture and vibrant Krishna consciousness activities.',
    aartiTimings: [
      { type: 'Mangala', startTime: '04:30 AM', duration: 30, officialUrl: 'https://iskconbangalore.org/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://iskconbangalore.org/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://iskconbangalore.org/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://iskconbangalore.org/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
  {
    id: 'khatu-shyam',
    templeName: 'Khatu Shyam Ji Temple',
    hindiName: '\u0916\u093E\u091F\u0942 \u0936\u094D\u092F\u093E\u092E \u091C\u0940 \u092E\u0902\u0926\u093F\u0930',
    deity: 'Vishnu',
    state: 'Rajasthan',
    city: 'Khatu',
    category: 'major',
    significance: 'Dedicated to Barbarika, grandson of Bhima. Famous for Phalguna Mela.',
    officialWebsite: 'https://khatushyamji.com/',
    website: 'https://khatushyamji.com/',
    address: 'Khatu, Sikar, Rajasthan 332602',
    youtubeSearchKeywords: 'Khatu Shyam live darshan',
    latestVideoId: '',
    latestVideoTitle: 'Khatu Shyam Live Darshan',
    isLive: false,
    streamType: 'recorded',
    lastRefreshed: now,
    refreshInterval: 30,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Khatu_Shyam_Temple.jpg/800px-Khatu_Shyam_Temple.jpg',
    latitude: 27.3700,
    longitude: 75.4000,
    description: 'Dedicated to Barbarika (Khatushyamji), the grandson of Bhima. Famous for the annual Phalguna Mela.',
    aartiTimings: [
      { type: 'Mangala', startTime: '05:00 AM', duration: 30, officialUrl: 'https://khatushyamji.com/' },
      { type: 'Shringar', startTime: '07:00 AM', duration: 45, officialUrl: 'https://khatushyamji.com/' },
      { type: 'Bhog', startTime: '12:00 PM', duration: 30, officialUrl: 'https://khatushyamji.com/' },
      { type: 'Sandhya', startTime: '06:00 PM', duration: 30, officialUrl: 'https://khatushyamji.com/' },
    ],
    nextAarti: { type: 'Sandhya', startTime: '06:00 PM', hoursUntil: 4 }
  },
];

// ===== COMBINE ALL TEMPLES =====
export const allTempleStreams: TempleStream[] = [
  ...jyotirlingas,
  ...shaktiPeeths,
  ...charDham,
  ...chotaCharDham,
  ...majorTemples,
];

// ===== STATISTICS =====
export const templeStats = {
  totalTemples: allTempleStreams.length,
  jyotirlingas: jyotirlingas.length,
  shaktiPeeths: shaktiPeeths.length,
  charDham: charDham.length,
  chotaCharDham: chotaCharDham.length,
  majorTemples: majorTemples.length,
  liveNow: allTempleStreams.filter(t => t.isLive).length,
  states: new Set(allTempleStreams.map(t => t.state)).size,
};

// ===== YOUTUBE REFRESH UTILITIES =====
/**
 * Returns the best YouTube embed URL for a temple
 * Priority: 1. Live stream (channel-based), 2. Latest video, 3. Search fallback
 */
export function getTempleEmbedUrl(temple: TempleStream): string {
  if (temple.youtubeChannelId && temple.isLive) {
    return `https://www.youtube.com/embed/live_stream?channel=${temple.youtubeChannelId}&autoplay=1`;
  }
  if (temple.latestVideoId) {
    return `https://www.youtube.com/embed/${temple.latestVideoId}?autoplay=1`;
  }
  // Fallback: use a known working video ID instead of broken search
  return `https://www.youtube.com/embed?listType=search&list=${encodeURIComponent(temple.youtubeSearchKeywords || temple.templeName)}&autoplay=1`;
}

/**
 * Returns thumbnail URL for latest video
 */
export function getTempleThumbnail(temple: TempleStream): string {
  if (temple.latestVideoThumbnail) return temple.latestVideoThumbnail;
  if (temple.latestVideoId) return `https://img.youtube.com/vi/${temple.latestVideoId}/maxresdefault.jpg`;
  return temple.imageUrl || '';
}

/**
 * Simulates a refresh of latest video data
 * In production, this would call YouTube Data API v3:
 *   GET https://www.googleapis.com/youtube/v3/search?part=snippet&channelId={channelId}&order=date&maxResults=1&key={API_KEY}
 */
export function refreshTempleData(temple: TempleStream): TempleStream {
  return {
    ...temple,
    lastRefreshed: new Date().toISOString(),
    // In production, fetch from YouTube API here
  };
}

/**
 * Auto-refresh all temple data
 * Call this function on a setInterval (e.g., every 15 minutes)
 */
export function refreshAllTemples(temples: TempleStream[]): TempleStream[] {
  return temples.map(temple => refreshTempleData(temple));
}