services:
  - type: web
    name: sanatan-sanskriti
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: VITE_SUPABASE_URL
        value: https://gvrbpvuucrzrbgnhtwoi.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_r59HlGOIlbXTdDaZuqlNxQ_xCrhaAG0