services:
  - type: web
    name: sanatan-sanskriti
    env: node
    region: singapore
    plan: free
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: NEXT_PUBLIC_SUPABASE_URL
        value: https://gvrbpvuucrzrbgnhtwoi.supabase.co
      - key: NEXT_PUBLIC_SUPABASE_SERVICE_ROLE_KEY
        value: YOUR_SECRET_KEY_HERE
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        value: sb_publishable_r59HlGOIlbXTdDaZuqlNxQ_xCrhaAG0
      - key: VITE_SUPABASE_URL
        value: https://gvrbpvuucrzrbgnhtwoi.supabase.co
      - key: VITE_SUPABASE_ANON_KEY
        value: sb_publishable_r59HlGOIlbXTdDaZuqlNxQ_xCrhaAG0
